kind: pipeline
type: docker
name: default

steps:
- name: build
  image: rust:latest
  commands:
  - cargo install du-dust 
    du-dust ripgrep fd-find 
    exa bat procs hyperfine 
    choose tealdeer sd 
    ytop bandwhich grex 
    --root /release
  - cd /release/bin && tar cJvf /release/rust-utils.tar.xz *
  volumes:
  - name: release 
    path: /release 

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: 
      - /release/rust-utils.tar.xz
      - /release/bin/*
  volumes:
  - name: release 
    path: /release 
  when:
    event: tag
    
volumes:
- name: release
  temp: {}
  