kind: pipeline
type: docker
name: default

steps:
- name: build
  image: rust:latest
  commands:
  - cargo install du-dust --root /release
  - tar cJvf /release/rust_utils.tar.xz /release/bin/*
  volumes:
  - name: release 
    path: /release 
#    du-dust ripgrep fd-find 
#    exa bat procs hyperfine 
#    choose tealdeer sd 
#    ytop bandwhich grex 

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: /release/rust_utils.tar.xz /release/bin/* 
  volumes:
  - name: release 
    path: /release 
  when:
    event: tag
    
volumes:
- name: release
  temp: {}
  