kind: pipeline
type: docker
name: default

steps:
- name: test
  image: rust:latest
  commands:
  - cargo install \ 
"du-dust" "ripgrep" "fd-find" \
"exa" "bat" "procs" "hyperfine" \
"choose" "tealdeer" "sd" \
"ytop" "bandwhich" "grex" 
  