kind: pipeline
type: docker
name: default

steps:
- name: build
  image: rust:latest
  commands:
  - cargo install du-dust 
    du-dust ripgrep fd-find 
    exa bat procs hyperfine 
    choose tealdeer sd 
    bandwhich grex 
    --root /release
  - curl https://github.com/soywod/himalaya/releases/download/v0.5.1/himalaya-linux.tar.gz -o himalaya.tar.gz
  - tar -xzf himalaya.tar.gz -C /release/bin
  - cd /release/bin && tar cvf /release/rust-utils.tar.xz *
  - cd /release/bin && tar cvf /release/rust-utils.tar.gz *
  volumes:
  - name: release 
    path: /release 

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: 
      - /release/rust-utils.tar.xz
      - /release/rust-utils.tar.gz
      - /release/bin/*
  volumes:
  - name: release 
    path: /release 
  when:
    event: tag
    
volumes:
- name: release
  temp: {}
  