name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
    - name: mkdir
      run: mkdir /release
    - name: Build
      run: > 
        cargo install du-dust  
        # du-dust ripgrep fd-find  
        # exa bat procs hyperfine  
        # choose tealdeer sd  
        # bandwhich grex   
        --root /release
    - name: Create archive
      run: |
        cd /release/bin && tar cvf /release/rust-utils.tar.xz *
        cd /release/bin && tar cvf /release/rust-utils.tar.gz *

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          /release/bin/*
          /release/rust-utils.tar.xz
          /release/rust-utils.tar.gz