name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
    - name: Build
      run: 
      - cargo install du-dust 
      du-dust ripgrep fd-find 
      exa bat procs hyperfine 
      choose tealdeer sd 
      bandwhich grex himalaya  

  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Publish 
      run: echo hello 